# Generated by Django 5.1.4 on 2025-01-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recipe",
            new_name="Receipe",
        ),
    ]
